# model_name: "unsloth/Qwen3-4B-Thinking-2507"
model_name: "Qwen/Qwen3-1.7B"
max_seq_length: 2048

training:
  learning_rate: 5e-6
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8

  num_train_epochs: 1
  num_generations: 4
  max_prompt_length: 1024
  max_completion_length: 1024

  logging_steps: 25
  save_steps: 50
  output_dir: "/outputs"
  report_to: "wandb"
  run_name: "proactive_grpo_classification"

  bf16: True
  max_grad_norm: 1.0
  # model_init_kwargs:
  #   torch_dtype: "bfloat16"
  gradient_checkpointing: False # Disable - use FSDP activation checkpointing instead

  # Optimizer
  optim: "adamw_torch"
  adam_beta1: 0.9
  adam_beta2: 0.99
  weight_decay: 0.01
  warmup_ratio: 0.05
  lr_scheduler_type: "cosine"

  # Data loading
  dataloader_num_workers: 4
  dataloader_pin_memory: True

  # Checkpointing
  save_total_limit: 3
  load_best_model_at_end: False

  # vLLLM
  use_vllm: True
  vllm_mode: "colocate"
  vllm_gpu_memory_utilization: 0.3
  vllm_enable_sleep_mode: True

reward_funcs:
  - name: "f1_score_reward"
    enabled: true
  - name: "accuracy_reward"
    enabled: true
  - name: "format_structure_reward"
    enabled: false
  - name: "category_validity_reward"
    enabled: true
  - name: "hamming_loss_reward"
    enabled: true
  - name: "squared_match_reward"
    enabled: true
